/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  docs: {
    'Getting Started': ['introduction', 'installation', 'quickstart', 'updating', 'troubleshoot'],
    'Building Bots': [
      'flows',
      'transitions',
      'timeouts',
      'intents',
      'utterances',
      'emulator',
      'carousel-postback',
      'channels',
      'chat-3rd-party-OAuth',
      'code',
      'content',
      '3rd-party-NLU',
      'about-pro',
      'analytics',
      'authentication',
      'carousel-postback',
      'channels',
      'chat-3rd-party-OAuth',
      'cluster-digital-ocean',
      'cluster',
      'code',
      'configuration',
      'content',
      'contextual-faq',
      'converse',
      'custom-module',
      'database',
      'debug',
      'development-pipeline',
      'dialog',
      'emulator',
      'existing-backend',
      'external-api',
      'faq',
      'flows',
      'hitl',
      'hosting',
      'i18n',
      'intent-matching',
      'intents',
      'interbot',
      'jump-to',
      'licensing',
      'listen-for-file-changes',
      'memory',
      'messenger',
      'migrate',
      'module',
      'monitoring',
      'nlu',
      'overview',
      'performances',
      'pipelines',
      'proactive',
      'rbac',
      'release-notes',
      'shortlinks',
      'skill-call-api',
      'skill-slot',
      'slack',
      'sync-changes',
      'teams',
      'telegram',
      'timeouts',
      'transitions',
      'uipath',
      'utterances',
      'versions',
      'web'
    ],
    'Deploying Botpress': ['configuration', 'cluster-digital-ocean', 'cluster'],
    'Managing Botpress': ['rbac', 'analytics', 'authentication']
  }
}
